name: Java CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Create deployment artifact
        run: |
          mkdir -p deployment
          cp target/*.jar deployment/
          cp -r terraform deployment/
          cp -r scripts deployment/

      - name: Archive deployment package
        uses: actions/upload-artifact@v3
        with:
          name: deployment-package
          path: deployment/